#下文有引用次配置，只能放到第一行，原因未知
common:
  ip: 192.168.0.214
  index: 1
mapIp: http://192.168.0.157:9009
#系统版本号
version: v-3.0.0
personArea: 410000
server:
  port: 8888
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${common.ip}:3306/facedb?characterEncoding=utf8&useSSL=false
      username: root
      password: CJ8AzTiVwZdJihNuyeYOeNpzeo1KndhRRlGr2wH5crWe9s4sYFbtGi5iUzva5l4YfBRqhz4zyGYv4miC8rjVww==
      #连接池的配置信息
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
      filter.config.enabled: true
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALBCiB/HyM/WdejJ+3ZPHLATs+/2QyLxBi+3Qx/ftXmYb3O4U3MyVMkmXjYbd8MKYj7WwXXCVzv0j8qxj7ejvSsCAwEAAQ==
      use-global-data-source-stat: true

#pagehelper分页插件配置
pagehelper:
  reasonable: true
  support-methods-arguments: false
  params: count=countSql
  helper-dialect: mysql

# 下划线到驼峰形式的映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ferret.bean
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

#上传文件/图片的保存路径,替换url路径
image:
  prefix:
    # 1.上传图片地址的路径目录前缀
    uploadDir: E:/ftpdata/upload
    historyDir: jh/face
    # 替换成url地址路径的前缀(IP后为IIS映射的头肩图虚拟目录)
    historyUrl: http://${common.ip}:7070/historypic/jh/face
    # 新中间件布控图片url地址前缀
    bukongImageUrl: http://${common.ip}:7070/controlpeoplepic/
    # 新中间件报警图片url地址前缀
    alarmImageUrl: http://${common.ip}:7070/alarmpic/
    # 新中间件抓拍图片url前缀
    historyImageUrl: http://${common.ip}:7070/historypic/
    # 新中间件抓拍图片实际存储路径(注意:请对应服务安装盘符)
    historyImageDir: D:/Face_Service/data/history/pic/
    # 新中间件接口请求地址前缀
    interfaceUrl:  http://${common.ip}:7070/
    # 图片抓拍后的存放路径(未处理)(注意:请对应服务安装盘符)
    makeCluserDir: D:/Face_Service/data/temp/gateway/
# 新中间件接口服务
interfaceservice:
  # 聚类反查接口
  clusterSearchUrl: http://${common.ip}:7070/ClusterIdQuery
  # 人脸特征提取
  faceFeatureExtraction: http://${common.ip}:7070/FaceSearch
socket:
  # 服务端通过tcp连接
  tcp:
    ip: ${common.ip}
    port:
      # 监控浏览端口
      monitor: 6901
      # 监控报警端口
      alarm: 4233
      # bukong: 9995
    #心跳间隔,单位秒
    heartbeat: 60
  # websocket通过http连接.
  web:
    url: /stomp
    destination-prefix:
    - /topic
    - /user
#修改聚集点分析：每次选择一个布控分组，每个布控分组对象不能高于一定值(默认200)
aggregationAnalyseNum: 200
# webservice 请求访问路径.
webservice:
  wsdlUrl: http://${common.ip}:7070/FaceTrails
#接口及数据配置文件配置
st:
  url: http://10.56.8.87:17210/renkoujichuku/cxgb
  formatDir: D:\\st_fmt.txt
identityCheck:
  checkerType: sj  #st省厅 sj市局
# 推送聚类数据开关
dataPush:
  # 0推送 1不推送
  sign: 1
  # 普通聚类数据推送url
  clusterDataPushUrl: http://127.0.0.1:8093/face/t111
  # 维族人数据推送url
  clusterWeiPushUrl: http://127.0.0.1:8093/face/t111
  # 报警数据推送url
  alarmPushUrl: http://127.0.0.1:8093/face/t111
  # 实时抓拍推送url
  realTimePushUrl: http://127.0.0.1:8093/face/t111
#同步市局身份接口url
synchronizeLdentityInterfaceUrl: http://10.56.12.156:8077/searchData
#异步省厅身份接口
asynchronousLdentityInterfaceUrl: http://10.56.10.211:8090/face/sendTask
#异步省厅身份获取接口
getAsynchronousLdentityInterfaceUrl: http://10.56.10.211:8090/face/faceCollect

#静态查询所需数据
static:
  #河南省厅常口静态接口
  HNSTStatic: http://10.56.12.156:8077/searchStatic
  #刑侦局前科静态接口
  XZJStatic: http://10.57.86.194:8077/searchStatic
#mqtt配置
mqtt:
  ip: ${common.ip}
  port: 1883
  username: admin
  password: 123456
  connectTimeOut: 30
  keepAlive: 60
#FTP配置
ftp:
  # sign  0推送，1不推送
  sign: 0
  ip: 192.168.1.146
  port: 21
  username: Administrator
  password: 0804807X
  pathname: ftp://192.168.1.146