
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ferret.webservice.client;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-17T11:27:43.943+08:00
 * Generated source VERSION: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "DynamicService",
                      portName = "DynamicServiceSoap",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://192.168.1.105/DynaService.asmx?wsdl",
                      endpointInterface = "com.ferret.webservice.client.DynamicServiceSoap")
                      
public class DynamicServiceSoapImpl implements DynamicServiceSoap {

    private static final Logger LOG = Logger.getLogger(DynamicServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.ferret.webservice.client.DynamicServiceSoap#queryHistoryFaceByImage(byte[] image, java.lang.String imageExt, javax.xml.datatype.XMLGregorianCalendar dtBegin, javax.xml.datatype.XMLGregorianCalendar dtEnd, float fLimit, int nWantNum)*
     */
    public com.ferret.webservice.client.ArrayOfQueryResult queryHistoryFaceByImage(byte[] image, java.lang.String imageExt, javax.xml.datatype.XMLGregorianCalendar dtBegin, javax.xml.datatype.XMLGregorianCalendar dtEnd, float fLimit, int nWantNum) {
        LOG.info("Executing operation queryHistoryFaceByImage");
        try {
            com.ferret.webservice.client.ArrayOfQueryResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ferret.webservice.client.DynamicServiceSoap#queryHistoryImage(java.lang.String cams, javax.xml.datatype.XMLGregorianCalendar dtBegin, javax.xml.datatype.XMLGregorianCalendar dtEnd)*
     */
    public com.ferret.webservice.client.ArrayOfHistoryImageInfo queryHistoryImage(java.lang.String cams, javax.xml.datatype.XMLGregorianCalendar dtBegin, javax.xml.datatype.XMLGregorianCalendar dtEnd) {
        LOG.info("Executing operation queryHistoryImage");
        System.out.println(cams);
        System.out.println(dtBegin);
        System.out.println(dtEnd);
        try {
            com.ferret.webservice.client.ArrayOfHistoryImageInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ferret.webservice.client.DynamicServiceSoap#getQueryResult(java.lang.String taskid)*
     */
    public com.ferret.webservice.client.QueryResult getQueryResult(java.lang.String taskid) {
        LOG.info("Executing operation getQueryResult");
        System.out.println(taskid);
        try {
            com.ferret.webservice.client.QueryResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ferret.webservice.client.DynamicServiceSoap#buKongPerson(byte[] imgData, java.lang.String extImag, java.lang.String idnum, java.lang.String name, java.lang.String desc, int alarmMethod, java.lang.String alarmAddr)*
     */
    public com.ferret.webservice.client.BuKongResult buKongPerson(byte[] imgData, java.lang.String extImag, java.lang.String idnum, java.lang.String name, java.lang.String desc, int alarmMethod, java.lang.String alarmAddr) {
        LOG.info("Executing operation buKongPerson");

        try {
            com.ferret.webservice.client.BuKongResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ferret.webservice.client.DynamicServiceSoap#commitQueryCmd(byte[] feature1, byte[] feature2, java.lang.String camIDs, javax.xml.datatype.XMLGregorianCalendar dtBegin, javax.xml.datatype.XMLGregorianCalendar dtEnd, float fLimit, int nWantNum)*
     */
    public java.lang.String commitQueryCmd(byte[] feature1, byte[] feature2, java.lang.String camIDs, javax.xml.datatype.XMLGregorianCalendar dtBegin, javax.xml.datatype.XMLGregorianCalendar dtEnd, float fLimit, int nWantNum) {
        LOG.info("Executing operation commitQueryCmd");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ferret.webservice.client.DynamicServiceSoap#userLogin()*
     */
    public java.lang.String userLogin() { 
        LOG.info("Executing operation userLogin");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ferret.webservice.client.DynamicServiceSoap#cancelBuKong(long id)*
     */
    public com.ferret.webservice.client.CancelBuKongResult cancelBuKong(long id) {
        LOG.info("Executing operation cancelBuKong");
        System.out.println(id);
        try {
            com.ferret.webservice.client.CancelBuKongResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ferret.webservice.client.DynamicServiceSoap#cancelQueryCmd(java.lang.String taskid)*
     */
    public void cancelQueryCmd(java.lang.String taskid) { 
        LOG.info("Executing operation cancelQueryCmd");
        System.out.println(taskid);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
