package com.ferret.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-17T11:27:43.975+08:00
 * Generated source VERSION: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "DynamicServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface DynamicServiceSoap {

    /**
     * 根据输入图像数据，查询历史结果
     */
    @WebMethod(operationName = "QueryHistoryFaceByImage", action = "http://tempuri.org/QueryHistoryFaceByImage")
    @RequestWrapper(localName = "QueryHistoryFaceByImage", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.QueryHistoryFaceByImage")
    @ResponseWrapper(localName = "QueryHistoryFaceByImageResponse", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.QueryHistoryFaceByImageResponse")
    @WebResult(name = "QueryHistoryFaceByImageResult", targetNamespace = "http://tempuri.org/")
    com.ferret.webservice.client.ArrayOfQueryResult queryHistoryFaceByImage(
            @WebParam(name = "image", targetNamespace = "http://tempuri.org/")
                    byte[] image,
            @WebParam(name = "imageExt", targetNamespace = "http://tempuri.org/")
                    java.lang.String imageExt,
            @WebParam(name = "dtBegin", targetNamespace = "http://tempuri.org/")
                    javax.xml.datatype.XMLGregorianCalendar dtBegin,
            @WebParam(name = "dtEnd", targetNamespace = "http://tempuri.org/")
                    javax.xml.datatype.XMLGregorianCalendar dtEnd,
            @WebParam(name = "fLimit", targetNamespace = "http://tempuri.org/")
                    float fLimit,
            @WebParam(name = "nWantNum", targetNamespace = "http://tempuri.org/")
                    int nWantNum
    );

    /**
     * 查询某个摄像头某段时间内的
     */
    @WebMethod(operationName = "QueryHistoryImage", action = "http://tempuri.org/QueryHistoryImage")
    @RequestWrapper(localName = "QueryHistoryImage", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.QueryHistoryImage")
    @ResponseWrapper(localName = "QueryHistoryImageResponse", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.QueryHistoryImageResponse")
    @WebResult(name = "QueryHistoryImageResult", targetNamespace = "http://tempuri.org/")
    com.ferret.webservice.client.ArrayOfHistoryImageInfo queryHistoryImage(
            @WebParam(name = "cams", targetNamespace = "http://tempuri.org/")
                    java.lang.String cams,
            @WebParam(name = "dtBegin", targetNamespace = "http://tempuri.org/")
                    javax.xml.datatype.XMLGregorianCalendar dtBegin,
            @WebParam(name = "dtEnd", targetNamespace = "http://tempuri.org/")
                    javax.xml.datatype.XMLGregorianCalendar dtEnd
    );

    /**
     * 异步获取查询结果
     */
    @WebMethod(operationName = "GetQueryResult", action = "http://tempuri.org/GetQueryResult")
    @RequestWrapper(localName = "GetQueryResult", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.GetQueryResult")
    @ResponseWrapper(localName = "GetQueryResultResponse", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.GetQueryResultResponse")
    @WebResult(name = "GetQueryResultResult", targetNamespace = "http://tempuri.org/")
    com.ferret.webservice.client.QueryResult getQueryResult(
            @WebParam(name = "taskid", targetNamespace = "http://tempuri.org/")
                    java.lang.String taskid
    );

    /**
     * 布控某个人员
     */
    @WebMethod(operationName = "BuKongPerson", action = "http://tempuri.org/BuKongPerson")
    @RequestWrapper(localName = "BuKongPerson", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.BuKongPerson")
    @ResponseWrapper(localName = "BuKongPersonResponse", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.BuKongPersonResponse")
    @WebResult(name = "BuKongPersonResult", targetNamespace = "http://tempuri.org/")
    com.ferret.webservice.client.BuKongResult buKongPerson(
            @WebParam(name = "imgData", targetNamespace = "http://tempuri.org/")
                    byte[] imgData,
            @WebParam(name = "extImag", targetNamespace = "http://tempuri.org/")
                    java.lang.String extImag,
            @WebParam(name = "idnum", targetNamespace = "http://tempuri.org/")
                    java.lang.String idnum,
            @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
                    java.lang.String name,
            @WebParam(name = "desc", targetNamespace = "http://tempuri.org/")
                    java.lang.String desc,
            @WebParam(name = "alarmMethod", targetNamespace = "http://tempuri.org/")
                    int alarmMethod,
            @WebParam(name = "alarmAddr", targetNamespace = "http://tempuri.org/")
                    java.lang.String alarmAddr
    );

    /**
     * 异步提交查询任务
     */
    @WebMethod(operationName = "CommitQueryCmd", action = "http://tempuri.org/CommitQueryCmd")
    @RequestWrapper(localName = "CommitQueryCmd", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.CommitQueryCmd")
    @ResponseWrapper(localName = "CommitQueryCmdResponse", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.CommitQueryCmdResponse")
    @WebResult(name = "CommitQueryCmdResult", targetNamespace = "http://tempuri.org/")
    java.lang.String commitQueryCmd(
            @WebParam(name = "feature1", targetNamespace = "http://tempuri.org/")
                    byte[] feature1,
            @WebParam(name = "feature2", targetNamespace = "http://tempuri.org/")
                    byte[] feature2,
            @WebParam(name = "camIDs", targetNamespace = "http://tempuri.org/")
                    java.lang.String camIDs,
            @WebParam(name = "dtBegin", targetNamespace = "http://tempuri.org/")
                    javax.xml.datatype.XMLGregorianCalendar dtBegin,
            @WebParam(name = "dtEnd", targetNamespace = "http://tempuri.org/")
                    javax.xml.datatype.XMLGregorianCalendar dtEnd,
            @WebParam(name = "fLimit", targetNamespace = "http://tempuri.org/")
                    float fLimit,
            @WebParam(name = "nWantNum", targetNamespace = "http://tempuri.org/")
                    int nWantNum
    );

    /**
     * 根据用户名和密码，获得权限树
     */
    @WebMethod(operationName = "UserLogin", action = "http://tempuri.org/UserLogin")
    @RequestWrapper(localName = "UserLogin", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.UserLogin")
    @ResponseWrapper(localName = "UserLoginResponse", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.UserLoginResponse")
    @WebResult(name = "UserLoginResult", targetNamespace = "http://tempuri.org/")
    java.lang.String userLogin();

    /**
     * 取消对某个人员的布控
     */
    @WebMethod(operationName = "CancelBuKong", action = "http://tempuri.org/CancelBuKong")
    @RequestWrapper(localName = "CancelBuKong", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.CancelBuKong")
    @ResponseWrapper(localName = "CancelBuKongResponse", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.CancelBuKongResponse")
    @WebResult(name = "CancelBuKongResult", targetNamespace = "http://tempuri.org/")
    com.ferret.webservice.client.CancelBuKongResult cancelBuKong(
            @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
                    long id
    );

    /**
     * 异步取消查询命令
     */
    @WebMethod(operationName = "CancelQueryCmd", action = "http://tempuri.org/CancelQueryCmd")
    @RequestWrapper(localName = "CancelQueryCmd", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.CancelQueryCmd")
    @ResponseWrapper(localName = "CancelQueryCmdResponse", targetNamespace = "http://tempuri.org/", className = "com.ferret.webservice.client.CancelQueryCmdResponse")
    void cancelQueryCmd(
            @WebParam(name = "taskid", targetNamespace = "http://tempuri.org/")
                    java.lang.String taskid
    );
}
